# Generated by Django 4.2.7 on 2023-11-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue_growth', models.CharField(max_length=100)),
                ('employees', models.CharField(max_length=100)),
                ('headquarters', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
